import Foundation

enum DockerComposeInjector {
    struct ServiceInfo: Identifiable, Hashable {
        var id: String { name }
        var name: String
        var existingExtraHosts: [String]
    }

    struct InjectionResult {
        var overrideURL: URL
        var certURL: URL
        var servicesTouched: [String]
    }

    /// Keys that belong to a service definition, not a service name.
    private static let reservedServiceKeys: Set<String> = [
        "image", "build", "ports", "volumes", "environment", "command", "depends_on",
        "restart", "networks", "extra_hosts", "labels", "healthcheck", "entrypoint",
        "working_dir", "user", "network_mode", "cap_add", "privileged", "tmpfs",
        "expose", "env_file", "profiles", "deploy", "logging", "container_name",
        "hostname", "shm_size", "ulimits", "sysctls", "devices", "dns", "links",
        "pid", "ipc", "stdin_open", "tty", "extends", "platform", "pull_policy",
    ]

    /// Pragmatic YAML scan: finds `services:` keys and any existing `extra_hosts`.
    /// Not a full YAML parser — sufficient for typical Compose files.
    static func parseServices(from yaml: String) -> [ServiceInfo] {
        let lines = yaml.components(separatedBy: "\n")
        var inServices = false
        var servicesIndent: Int?
        var serviceIndent: Int?
        var currentName: String?
        var currentHosts: [String] = []
        var inExtraHosts = false
        var results: [ServiceInfo] = []

        func flush() {
            if let currentName {
                results.append(ServiceInfo(name: currentName, existingExtraHosts: currentHosts))
            }
            currentName = nil
            currentHosts = []
            inExtraHosts = false
        }

        for raw in lines {
            let trimmed = raw.trimmingCharacters(in: .whitespaces)
            if trimmed.isEmpty || trimmed.hasPrefix("#") { continue }
            let indent = raw.prefix(while: { $0 == " " }).count

            if !inServices {
                if trimmed.hasPrefix("services:") {
                    inServices = true
                    servicesIndent = indent
                }
                continue
            }

            guard let servicesIndent else { continue }

            if indent <= servicesIndent && !trimmed.hasPrefix("services:") {
                flush()
                break
            }

            if trimmed.hasSuffix(":"), !trimmed.hasPrefix("-") {
                let key = String(trimmed.dropLast())
                if indent == servicesIndent + 2, !reservedServiceKeys.contains(key) {
                    flush()
                    currentName = key
                    serviceIndent = indent
                    continue
                }
            }

            guard currentName != nil, let serviceIndent else { continue }

            if trimmed.hasPrefix("extra_hosts:") {
                inExtraHosts = true
                continue
            }

            if inExtraHosts {
                if trimmed.hasPrefix("-") {
                    var value = trimmed.dropFirst().trimmingCharacters(in: .whitespaces)
                    value = value.trimmingCharacters(in: CharacterSet(charactersIn: "\"'"))
                    currentHosts.append(value)
                } else if indent <= serviceIndent + 2 && trimmed.hasSuffix(":") {
                    inExtraHosts = false
                } else if indent <= serviceIndent {
                    inExtraHosts = false
                }
            }
        }

        flush()
        return results
    }

    static func inject(
        composeFileURL: URL,
        selectedServices: Set<String>,
        domains: [String],
        rootCertURL: URL
    ) throws -> InjectionResult {
        let directory = composeFileURL.deletingLastPathComponent()
        let certDest = directory.appendingPathComponent(".caddymanager-root-ca.crt")
        let overrideURL = directory.appendingPathComponent("docker-compose.override.yml")

        let certData = try Data(contentsOf: rootCertURL)
        try certData.write(to: certDest, options: .atomic)

        let yamlText = try String(contentsOf: composeFileURL, encoding: .utf8)
        let services = parseServices(from: yamlText)
        let selected = services.filter { selectedServices.contains($0.name) }
        guard !selected.isEmpty else {
            throw NSError(domain: "DockerComposeInjector", code: 1, userInfo: [
                NSLocalizedDescriptionKey: "No services selected.",
            ])
        }

        var lines: [String] = [
            "# Auto-generated by CaddyManager — merges with docker-compose.yml",
            "services:",
        ]

        for service in selected {
            lines.append("  \(service.name):")
            lines.append("    volumes:")
            lines.append("      - ./.caddymanager-root-ca.crt:/usr/local/share/ca-certificates/caddymanager-root-ca.crt:ro")
            let newHosts = domains.filter { domain in
                !service.existingExtraHosts.contains(where: {
                    $0 == domain || $0.hasPrefix("\(domain):")
                })
            }
            if !newHosts.isEmpty {
                lines.append("    extra_hosts:")
                for domain in newHosts {
                    lines.append("      - \"\(domain):host-gateway\"")
                }
            }
            lines.append("")
        }

        try lines.joined(separator: "\n").write(to: overrideURL, atomically: true, encoding: .utf8)

        return InjectionResult(
            overrideURL: overrideURL,
            certURL: certDest,
            servicesTouched: selected.map(\.name)
        )
    }
}
